version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.12.1
    filters:
      branches:
        only: [main, develop]
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm test
